# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NationalMonumentsPortugal
                                 A QGIS plugin
 This plugin displays Portuguese Monuments' coordinates in the Map
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-04
        copyright            : (C) 2021 by André Pereira, João Santos
        email                : joao-santos-26@outlook.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NationalMonumentsPortugal class from file NationalMonumentsPortugal.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .national_monuments_portugal import NationalMonumentsPortugal
    return NationalMonumentsPortugal(iface)
